services:
  app_product:
    build:
      context: .
    container_name: product_app
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db_product:3306/dto_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_USER_NAME: miguel
      DB_PASSWORD: miguelelmejor
    restart: always
    depends_on:
      db_product:
        condition: service_healthy

  db_product:
    image: mysql:8.0.33
    container_name: product_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: miguelelmejor
      MYSQL_DATABASE: dto_db
      MYSQL_USER: miguel
      MYSQL_PASSWORD: miguelelmejor
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
